apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdf-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pdf-service
  template:
    metadata:
      labels:
        app: pdf-service
    spec:
      containers:
        - image: zigakleine/pdf-service:1.0.0-SNAPSHOT-15.1
          resources:
            requests:
              cpu: "50m"
            limits:
              cpu: "60m"
          name: pdf-service
          ports:
            - containerPort: 8085
              name: server
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/v1/checks/health/liveness
              port: server
            initialDelaySeconds: 360
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /api/v1/checks/health/readiness
              port: server
            initialDelaySeconds: 360
            periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: pdf-service
spec:
  type: LoadBalancer
  ports:
    - port: 8085
      protocol: TCP
      targetPort: server
  selector:
    app: pdf-service